//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetTarget) DeepCopyInto(out *NetTarget) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(TargetService)
		(*in).DeepCopyInto(*out)
	}
	if in.HostAddress != nil {
		in, out := &in.HostAddress, &out.HostAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetTarget.
func (in *NetTarget) DeepCopy() *NetTarget {
	if in == nil {
		return nil
	}
	out := new(NetTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Netdoctor) DeepCopyInto(out *Netdoctor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Netdoctor.
func (in *Netdoctor) DeepCopy() *Netdoctor {
	if in == nil {
		return nil
	}
	out := new(Netdoctor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Netdoctor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdoctorList) DeepCopyInto(out *NetdoctorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Netdoctor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdoctorList.
func (in *NetdoctorList) DeepCopy() *NetdoctorList {
	if in == nil {
		return nil
	}
	out := new(NetdoctorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetdoctorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdoctorSpec) DeepCopyInto(out *NetdoctorSpec) {
	*out = *in
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(SchedulePlan)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(NetTarget)
		(*in).DeepCopyInto(*out)
	}
	if in.TestIPv4 != nil {
		in, out := &in.TestIPv4, &out.TestIPv4
		*out = new(bool)
		**out = **in
	}
	if in.TestIPv6 != nil {
		in, out := &in.TestIPv6, &out.TestIPv6
		*out = new(bool)
		**out = **in
	}
	if in.EachTimeInSecond != nil {
		in, out := &in.EachTimeInSecond, &out.EachTimeInSecond
		*out = new(uint64)
		**out = **in
	}
	if in.EachQPS != nil {
		in, out := &in.EachQPS, &out.EachQPS
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdoctorSpec.
func (in *NetdoctorSpec) DeepCopy() *NetdoctorSpec {
	if in == nil {
		return nil
	}
	out := new(NetdoctorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdoctorStatus) DeepCopyInto(out *NetdoctorStatus) {
	*out = *in
	if in.DoneRound != nil {
		in, out := &in.DoneRound, &out.DoneRound
		*out = new(int64)
		**out = **in
	}
	if in.LastRoundFinishTimeStamp != nil {
		in, out := &in.LastRoundFinishTimeStamp, &out.LastRoundFinishTimeStamp
		*out = (*in).DeepCopy()
	}
	if in.LastRoundStatus != nil {
		in, out := &in.LastRoundStatus, &out.LastRoundStatus
		*out = new(string)
		**out = **in
	}
	if in.NextRoundStartTimeStamp != nil {
		in, out := &in.NextRoundStartTimeStamp, &out.NextRoundStartTimeStamp
		*out = (*in).DeepCopy()
	}
	if in.NextRoundDeadLineTimeStamp != nil {
		in, out := &in.NextRoundDeadLineTimeStamp, &out.NextRoundDeadLineTimeStamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdoctorStatus.
func (in *NetdoctorStatus) DeepCopy() *NetdoctorStatus {
	if in == nil {
		return nil
	}
	out := new(NetdoctorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulePlan) DeepCopyInto(out *SchedulePlan) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulePlan.
func (in *SchedulePlan) DeepCopy() *SchedulePlan {
	if in == nil {
		return nil
	}
	out := new(SchedulePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetService) DeepCopyInto(out *TargetService) {
	*out = *in
	if in.TestEndpoint != nil {
		in, out := &in.TestEndpoint, &out.TestEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.TestNodePort != nil {
		in, out := &in.TestNodePort, &out.TestNodePort
		*out = new(bool)
		**out = **in
	}
	if in.TestIngress != nil {
		in, out := &in.TestIngress, &out.TestIngress
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetService.
func (in *TargetService) DeepCopy() *TargetService {
	if in == nil {
		return nil
	}
	out := new(TargetService)
	in.DeepCopyInto(out)
	return out
}
