// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/spidernet-io/spiderdoctor/pkg/k8s/apis/spiderdoctor.spidernet.io/v1"
	scheme "github.com/spidernet-io/spiderdoctor/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetdoctorsGetter has a method to return a NetdoctorInterface.
// A group's client should implement this interface.
type NetdoctorsGetter interface {
	Netdoctors() NetdoctorInterface
}

// NetdoctorInterface has methods to work with Netdoctor resources.
type NetdoctorInterface interface {
	Create(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.CreateOptions) (*v1.Netdoctor, error)
	Update(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.UpdateOptions) (*v1.Netdoctor, error)
	UpdateStatus(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.UpdateOptions) (*v1.Netdoctor, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Netdoctor, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.NetdoctorList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Netdoctor, err error)
	NetdoctorExpansion
}

// netdoctors implements NetdoctorInterface
type netdoctors struct {
	client rest.Interface
}

// newNetdoctors returns a Netdoctors
func newNetdoctors(c *SpiderdoctorV1Client) *netdoctors {
	return &netdoctors{
		client: c.RESTClient(),
	}
}

// Get takes name of the netdoctor, and returns the corresponding netdoctor object, and an error if there is any.
func (c *netdoctors) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Netdoctor, err error) {
	result = &v1.Netdoctor{}
	err = c.client.Get().
		Resource("netdoctors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Netdoctors that match those selectors.
func (c *netdoctors) List(ctx context.Context, opts metav1.ListOptions) (result *v1.NetdoctorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.NetdoctorList{}
	err = c.client.Get().
		Resource("netdoctors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested netdoctors.
func (c *netdoctors) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("netdoctors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a netdoctor and creates it.  Returns the server's representation of the netdoctor, and an error, if there is any.
func (c *netdoctors) Create(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.CreateOptions) (result *v1.Netdoctor, err error) {
	result = &v1.Netdoctor{}
	err = c.client.Post().
		Resource("netdoctors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdoctor).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a netdoctor and updates it. Returns the server's representation of the netdoctor, and an error, if there is any.
func (c *netdoctors) Update(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.UpdateOptions) (result *v1.Netdoctor, err error) {
	result = &v1.Netdoctor{}
	err = c.client.Put().
		Resource("netdoctors").
		Name(netdoctor.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdoctor).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *netdoctors) UpdateStatus(ctx context.Context, netdoctor *v1.Netdoctor, opts metav1.UpdateOptions) (result *v1.Netdoctor, err error) {
	result = &v1.Netdoctor{}
	err = c.client.Put().
		Resource("netdoctors").
		Name(netdoctor.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(netdoctor).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the netdoctor and deletes it. Returns an error if one occurs.
func (c *netdoctors) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("netdoctors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *netdoctors) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("netdoctors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched netdoctor.
func (c *netdoctors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Netdoctor, err error) {
	result = &v1.Netdoctor{}
	err = c.client.Patch(pt).
		Resource("netdoctors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
