// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSpiderdoctoragentParams creates a new GetSpiderdoctoragentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSpiderdoctoragentParams() *GetSpiderdoctoragentParams {
	return &GetSpiderdoctoragentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSpiderdoctoragentParamsWithTimeout creates a new GetSpiderdoctoragentParams object
// with the ability to set a timeout on a request.
func NewGetSpiderdoctoragentParamsWithTimeout(timeout time.Duration) *GetSpiderdoctoragentParams {
	return &GetSpiderdoctoragentParams{
		timeout: timeout,
	}
}

// NewGetSpiderdoctoragentParamsWithContext creates a new GetSpiderdoctoragentParams object
// with the ability to set a context for a request.
func NewGetSpiderdoctoragentParamsWithContext(ctx context.Context) *GetSpiderdoctoragentParams {
	return &GetSpiderdoctoragentParams{
		Context: ctx,
	}
}

// NewGetSpiderdoctoragentParamsWithHTTPClient creates a new GetSpiderdoctoragentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSpiderdoctoragentParamsWithHTTPClient(client *http.Client) *GetSpiderdoctoragentParams {
	return &GetSpiderdoctoragentParams{
		HTTPClient: client,
	}
}

/*
GetSpiderdoctoragentParams contains all the parameters to send to the API endpoint

	for the get spiderdoctoragent operation.

	Typically these are written to a http.Request.
*/
type GetSpiderdoctoragentParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get spiderdoctoragent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSpiderdoctoragentParams) WithDefaults() *GetSpiderdoctoragentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get spiderdoctoragent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSpiderdoctoragentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) WithTimeout(timeout time.Duration) *GetSpiderdoctoragentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) WithContext(ctx context.Context) *GetSpiderdoctoragentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) WithHTTPClient(client *http.Client) *GetSpiderdoctoragentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get spiderdoctoragent params
func (o *GetSpiderdoctoragentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSpiderdoctoragentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
