// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spidernet-io/spiderdoctor/api/v1/agentServer/models"
)

// GetSpiderdoctoragentOKCode is the HTTP code returned for type GetSpiderdoctoragentOK
const GetSpiderdoctoragentOKCode int = 200

/*
GetSpiderdoctoragentOK Success

swagger:response getSpiderdoctoragentOK
*/
type GetSpiderdoctoragentOK struct {

	/*
	  In: Body
	*/
	Payload *models.EchoRes `json:"body,omitempty"`
}

// NewGetSpiderdoctoragentOK creates GetSpiderdoctoragentOK with default headers values
func NewGetSpiderdoctoragentOK() *GetSpiderdoctoragentOK {

	return &GetSpiderdoctoragentOK{}
}

// WithPayload adds the payload to the get spiderdoctoragent o k response
func (o *GetSpiderdoctoragentOK) WithPayload(payload *models.EchoRes) *GetSpiderdoctoragentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get spiderdoctoragent o k response
func (o *GetSpiderdoctoragentOK) SetPayload(payload *models.EchoRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSpiderdoctoragentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
