// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package echo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSpiderdoctoragentHandlerFunc turns a function with the right signature into a get spiderdoctoragent handler
type GetSpiderdoctoragentHandlerFunc func(GetSpiderdoctoragentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSpiderdoctoragentHandlerFunc) Handle(params GetSpiderdoctoragentParams) middleware.Responder {
	return fn(params)
}

// GetSpiderdoctoragentHandler interface for that can handle valid get spiderdoctoragent params
type GetSpiderdoctoragentHandler interface {
	Handle(GetSpiderdoctoragentParams) middleware.Responder
}

// NewGetSpiderdoctoragent creates a new http.Handler for the get spiderdoctoragent operation
func NewGetSpiderdoctoragent(ctx *middleware.Context, handler GetSpiderdoctoragentHandler) *GetSpiderdoctoragent {
	return &GetSpiderdoctoragent{Context: ctx, Handler: handler}
}

/*
	GetSpiderdoctoragent swagger:route GET /spiderdoctoragent echo getSpiderdoctoragent

echo http request

echo http request
*/
type GetSpiderdoctoragent struct {
	Context *middleware.Context
	Handler GetSpiderdoctoragentHandler
}

func (o *GetSpiderdoctoragent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSpiderdoctoragentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
