// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// NetdnsListerExpansion allows custom methods to be added to
// NetdnsLister.
type NetdnsListerExpansion interface{}

// NethttpListerExpansion allows custom methods to be added to
// NethttpLister.
type NethttpListerExpansion interface{}
