// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// NetdoctorListerExpansion allows custom methods to be added to
// NetdoctorLister.
type NetdoctorListerExpansion interface{}
