// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/spiderdoctor/pkg/k8s/apis/spiderdoctor.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NetdoctorLister helps list Netdoctors.
// All objects returned here must be treated as read-only.
type NetdoctorLister interface {
	// List lists all Netdoctors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Netdoctor, err error)
	// Get retrieves the Netdoctor from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Netdoctor, error)
	NetdoctorListerExpansion
}

// netdoctorLister implements the NetdoctorLister interface.
type netdoctorLister struct {
	indexer cache.Indexer
}

// NewNetdoctorLister returns a new NetdoctorLister.
func NewNetdoctorLister(indexer cache.Indexer) NetdoctorLister {
	return &netdoctorLister{indexer: indexer}
}

// List lists all Netdoctors in the indexer.
func (s *netdoctorLister) List(selector labels.Selector) (ret []*v1.Netdoctor, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Netdoctor))
	})
	return ret, err
}

// Get retrieves the Netdoctor from the index for a given name.
func (s *netdoctorLister) Get(name string) (*v1.Netdoctor, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("netdoctor"), name)
	}
	return obj.(*v1.Netdoctor), nil
}
