// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/spidernet-io/spiderdoctor/pkg/k8s/apis/spiderdoctor.spidernet.io/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NethttpLister helps list Nethttps.
// All objects returned here must be treated as read-only.
type NethttpLister interface {
	// List lists all Nethttps in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Nethttp, err error)
	// Get retrieves the Nethttp from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Nethttp, error)
	NethttpListerExpansion
}

// nethttpLister implements the NethttpLister interface.
type nethttpLister struct {
	indexer cache.Indexer
}

// NewNethttpLister returns a new NethttpLister.
func NewNethttpLister(indexer cache.Indexer) NethttpLister {
	return &nethttpLister{indexer: indexer}
}

// List lists all Nethttps in the indexer.
func (s *nethttpLister) List(selector labels.Selector) (ret []*v1.Nethttp, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.Nethttp))
	})
	return ret, err
}

// Get retrieves the Nethttp from the index for a given name.
func (s *nethttpLister) Get(name string) (*v1.Nethttp, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("nethttp"), name)
	}
	return obj.(*v1.Nethttp), nil
}
