// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/spidernet-io/spiderdoctor/pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1"
	scheme "github.com/spidernet-io/spiderdoctor/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NethttpsGetter has a method to return a NethttpInterface.
// A group's client should implement this interface.
type NethttpsGetter interface {
	Nethttps() NethttpInterface
}

// NethttpInterface has methods to work with Nethttp resources.
type NethttpInterface interface {
	Create(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.CreateOptions) (*v1beta1.Nethttp, error)
	Update(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.UpdateOptions) (*v1beta1.Nethttp, error)
	UpdateStatus(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.UpdateOptions) (*v1beta1.Nethttp, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.Nethttp, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.NethttpList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Nethttp, err error)
	NethttpExpansion
}

// nethttps implements NethttpInterface
type nethttps struct {
	client rest.Interface
}

// newNethttps returns a Nethttps
func newNethttps(c *SpiderdoctorV1beta1Client) *nethttps {
	return &nethttps{
		client: c.RESTClient(),
	}
}

// Get takes name of the nethttp, and returns the corresponding nethttp object, and an error if there is any.
func (c *nethttps) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Nethttp, err error) {
	result = &v1beta1.Nethttp{}
	err = c.client.Get().
		Resource("nethttps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Nethttps that match those selectors.
func (c *nethttps) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NethttpList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.NethttpList{}
	err = c.client.Get().
		Resource("nethttps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nethttps.
func (c *nethttps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("nethttps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nethttp and creates it.  Returns the server's representation of the nethttp, and an error, if there is any.
func (c *nethttps) Create(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.CreateOptions) (result *v1beta1.Nethttp, err error) {
	result = &v1beta1.Nethttp{}
	err = c.client.Post().
		Resource("nethttps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nethttp).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nethttp and updates it. Returns the server's representation of the nethttp, and an error, if there is any.
func (c *nethttps) Update(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.UpdateOptions) (result *v1beta1.Nethttp, err error) {
	result = &v1beta1.Nethttp{}
	err = c.client.Put().
		Resource("nethttps").
		Name(nethttp.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nethttp).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nethttps) UpdateStatus(ctx context.Context, nethttp *v1beta1.Nethttp, opts v1.UpdateOptions) (result *v1beta1.Nethttp, err error) {
	result = &v1beta1.Nethttp{}
	err = c.client.Put().
		Resource("nethttps").
		Name(nethttp.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nethttp).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nethttp and deletes it. Returns an error if one occurs.
func (c *nethttps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("nethttps").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nethttps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("nethttps").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nethttp.
func (c *nethttps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Nethttp, err error) {
	result = &v1beta1.Nethttp{}
	err = c.client.Patch(pt).
		Resource("nethttps").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
